<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Configuration\Configuration.csproj" />
    <ProjectReference Include="..\DbRepos\DbRepos.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
  </ItemGroup>
</Project>
